
import os
import torch
import torch.nn as nn
import torch.optim as optim
import cv2
import subprocess
from torch.utils.data import DataLoader
from src.audio_utils import process_audio_pipeline
from src.dataset import MultiModalSyncDataset
from src.model import LipSyncAutoencoder

def run_sync_india_pipeline(video_path, target_lang="hi", epochs=5, status_callback=None):
    base_dir = os.path.abspath(os.getcwd())
    outputs_dir = os.path.join(base_dir, "outputs")
    processed_dir = os.path.join(base_dir, "data", "processed")
    os.makedirs(outputs_dir, exist_ok=True)
    os.makedirs(processed_dir, exist_ok=True)

    if status_callback: status_callback("🔊 Extracting & translating multi-modal tracks...")
    translated_wav = process_audio_pipeline(video_path, target_lang=target_lang)
    
    if status_callback: status_callback("📊 Initializing dynamic tensor dataset mapping...")
    dataset = MultiModalSyncDataset(video_path, translated_wav)
    dataloader = DataLoader(dataset, batch_size=4, shuffle=False)
    
    if status_callback: status_callback("🧠 Constructing Neural Network Layers...")
    model = LipSyncAutoencoder()
    criterion = nn.L1Loss() 
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    
    # Active Person-Specific Optimization Loop
    model.train()
    for epoch in range(epochs):
        epoch_loss = 0.0
        for masked_face, orig_face, audio_feat in dataloader:
            optimizer.zero_grad()
            predictions = model(masked_face, audio_feat)
            loss = criterion(predictions, orig_face)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
        if status_callback: 
            status_callback(f"🏋️ Training Viseme Layers | Epoch {epoch+1}/{epochs} | Loss: {epoch_loss/len(dataloader):.4f}")
            
    if status_callback: status_callback("🎬 Synthesizing localized output frames...")
    model.eval()
    
    temp_output_avi = os.path.abspath(os.path.join(outputs_dir, "temp_render.avi"))
    
    # Read original video spatial dimensions from our stored HD dataset frames
    sample_hd_frame = dataset.raw_hd_frames[0]
    hd_height, hd_width, _ = sample_hd_frame.shape
    
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out_video = cv2.VideoWriter()
    out_video.open(temp_output_avi, fourcc, 25.0, (hd_width, hd_height))
    
    frame_idx = 0
    with torch.no_grad():
        for masked_face, _, audio_feat in dataloader:
            predictions = model(masked_face, audio_feat)
            for pred in predictions:
                if frame_idx >= len(dataset.raw_hd_frames):
                    break
                
                # 1. Fetch the completely untouched, sharp HD background frame
                hd_frame = dataset.raw_hd_frames[frame_idx].copy()
                
                # 2. Extract the AI's generated small mouth tensor and scale it to 0-255 bytes
                ai_mouth_small = pred.permute(1, 2, 0).numpy() * 255.0
                ai_mouth_small = cv2.convertScaleAbs(ai_mouth_small)
                
                # 3. Resize ONLY the AI mouth back up to the exact dimensions of the HD frame
                ai_mouth_hd = cv2.resize(ai_mouth_small, (hd_width, hd_height))
                
                # 4. Math Overlay: Take the top 55% of the original sharp video (eyes/hair/background)
                # and stitch it seamlessly to the bottom 45% generated by the AI (the newly synchronized lips)
                split_line = int(hd_height * 0.55)
                combined_frame = hd_frame.copy()
                combined_frame[split_line:, :] = ai_mouth_hd[split_line:, :]
                
                # Optional: Smooth the hard cut line using a minor spatial blur along the seam boundary
                cv2.GaussianBlur(combined_frame[split_line-4:split_line+4, :], (1, 5), 0)
                
                out_video.write(combined_frame)
                frame_idx += 1
                
    out_video.release()
    
    final_output_mp4 = os.path.abspath(os.path.join(outputs_dir, f"synchronized_{target_lang}.mp4"))
    mux_command = f'ffmpeg -y -i "{temp_output_avi}" -i "{translated_wav}" -c:v libx264 -c:a aac -strict experimental "{final_output_mp4}"'
    subprocess.call(mux_command, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    return final_output_mp4